/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'
import { Route as AppCampaignsCampaignIdRouteImport } from './routes/_app.campaigns.$campaignId'
import { Route as AppCampaignsCampaignIdIndexRouteImport } from './routes/_app.campaigns.$campaignId.index'
import { Route as AppCampaignsCampaignIdTimelineRouteImport } from './routes/_app.campaigns.$campaignId.timeline'
import { Route as AppCampaignsCampaignIdSettingsRouteImport } from './routes/_app.campaigns.$campaignId.settings'
import { Route as AppCampaignsCampaignIdSessionsRouteImport } from './routes/_app.campaigns.$campaignId.sessions'
import { Route as AppCampaignsCampaignIdNounsRouteImport } from './routes/_app.campaigns.$campaignId.nouns'
import { Route as AppCampaignsCampaignIdEditRouteImport } from './routes/_app.campaigns.$campaignId.edit'
import { Route as AppCampaignsCampaignIdSessionsIndexRouteImport } from './routes/_app.campaigns.$campaignId.sessions.index'
import { Route as AppCampaignsCampaignIdNounsIndexRouteImport } from './routes/_app.campaigns.$campaignId.nouns.index'
import { Route as AppCampaignsCampaignIdMapsIndexRouteImport } from './routes/_app.campaigns.$campaignId.maps.index'
import { Route as AppCampaignsCampaignIdSessionsNewRouteImport } from './routes/_app.campaigns.$campaignId.sessions.new'
import { Route as AppCampaignsCampaignIdSessionsSessionIdRouteImport } from './routes/_app.campaigns.$campaignId.sessions.$sessionId'
import { Route as AppCampaignsCampaignIdNounsNewRouteImport } from './routes/_app.campaigns.$campaignId.nouns.new'
import { Route as AppCampaignsCampaignIdNounsNounIdRouteImport } from './routes/_app.campaigns.$campaignId.nouns.$nounId'
import { Route as AppCampaignsCampaignIdMapsNewRouteImport } from './routes/_app.campaigns.$campaignId.maps.new'
import { Route as AppCampaignsCampaignIdMapsMapIdRouteImport } from './routes/_app.campaigns.$campaignId.maps.$mapId'
import { Route as AppCampaignsCampaignIdSessionsSessionIdIndexRouteImport } from './routes/_app.campaigns.$campaignId.sessions.$sessionId.index'
import { Route as AppCampaignsCampaignIdNounsNounIdIndexRouteImport } from './routes/_app.campaigns.$campaignId.nouns.$nounId.index'
import { Route as AppCampaignsCampaignIdMapsMapIdIndexRouteImport } from './routes/_app.campaigns.$campaignId.maps.$mapId.index'
import { Route as AppCampaignsCampaignIdSessionsSessionIdEditRouteImport } from './routes/_app.campaigns.$campaignId.sessions.$sessionId.edit'
import { Route as AppCampaignsCampaignIdNounsNounIdEditRouteImport } from './routes/_app.campaigns.$campaignId.nouns.$nounId.edit'
import { Route as AppCampaignsCampaignIdMapsMapIdEditRouteImport } from './routes/_app.campaigns.$campaignId.maps.$mapId.edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsCampaignIdRoute = AppCampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsCampaignIdIndexRoute =
  AppCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdTimelineRoute =
  AppCampaignsCampaignIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdSettingsRoute =
  AppCampaignsCampaignIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdSessionsRoute =
  AppCampaignsCampaignIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdNounsRoute =
  AppCampaignsCampaignIdNounsRouteImport.update({
    id: '/nouns',
    path: '/nouns',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdEditRoute =
  AppCampaignsCampaignIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdSessionsIndexRoute =
  AppCampaignsCampaignIdSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCampaignsCampaignIdSessionsRoute,
  } as any)
const AppCampaignsCampaignIdNounsIndexRoute =
  AppCampaignsCampaignIdNounsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCampaignsCampaignIdNounsRoute,
  } as any)
const AppCampaignsCampaignIdMapsIndexRoute =
  AppCampaignsCampaignIdMapsIndexRouteImport.update({
    id: '/maps/',
    path: '/maps/',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdSessionsNewRoute =
  AppCampaignsCampaignIdSessionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppCampaignsCampaignIdSessionsRoute,
  } as any)
const AppCampaignsCampaignIdSessionsSessionIdRoute =
  AppCampaignsCampaignIdSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AppCampaignsCampaignIdSessionsRoute,
  } as any)
const AppCampaignsCampaignIdNounsNewRoute =
  AppCampaignsCampaignIdNounsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppCampaignsCampaignIdNounsRoute,
  } as any)
const AppCampaignsCampaignIdNounsNounIdRoute =
  AppCampaignsCampaignIdNounsNounIdRouteImport.update({
    id: '/$nounId',
    path: '/$nounId',
    getParentRoute: () => AppCampaignsCampaignIdNounsRoute,
  } as any)
const AppCampaignsCampaignIdMapsNewRoute =
  AppCampaignsCampaignIdMapsNewRouteImport.update({
    id: '/maps/new',
    path: '/maps/new',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdMapsMapIdRoute =
  AppCampaignsCampaignIdMapsMapIdRouteImport.update({
    id: '/maps/$mapId',
    path: '/maps/$mapId',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdSessionsSessionIdIndexRoute =
  AppCampaignsCampaignIdSessionsSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCampaignsCampaignIdSessionsSessionIdRoute,
  } as any)
const AppCampaignsCampaignIdNounsNounIdIndexRoute =
  AppCampaignsCampaignIdNounsNounIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCampaignsCampaignIdNounsNounIdRoute,
  } as any)
const AppCampaignsCampaignIdMapsMapIdIndexRoute =
  AppCampaignsCampaignIdMapsMapIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCampaignsCampaignIdMapsMapIdRoute,
  } as any)
const AppCampaignsCampaignIdSessionsSessionIdEditRoute =
  AppCampaignsCampaignIdSessionsSessionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppCampaignsCampaignIdSessionsSessionIdRoute,
  } as any)
const AppCampaignsCampaignIdNounsNounIdEditRoute =
  AppCampaignsCampaignIdNounsNounIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppCampaignsCampaignIdNounsNounIdRoute,
  } as any)
const AppCampaignsCampaignIdMapsMapIdEditRoute =
  AppCampaignsCampaignIdMapsMapIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppCampaignsCampaignIdMapsMapIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/campaigns/$campaignId/edit': typeof AppCampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/nouns': typeof AppCampaignsCampaignIdNounsRouteWithChildren
  '/campaigns/$campaignId/sessions': typeof AppCampaignsCampaignIdSessionsRouteWithChildren
  '/campaigns/$campaignId/settings': typeof AppCampaignsCampaignIdSettingsRoute
  '/campaigns/$campaignId/timeline': typeof AppCampaignsCampaignIdTimelineRoute
  '/campaigns/$campaignId/': typeof AppCampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/maps/$mapId': typeof AppCampaignsCampaignIdMapsMapIdRouteWithChildren
  '/campaigns/$campaignId/maps/new': typeof AppCampaignsCampaignIdMapsNewRoute
  '/campaigns/$campaignId/nouns/$nounId': typeof AppCampaignsCampaignIdNounsNounIdRouteWithChildren
  '/campaigns/$campaignId/nouns/new': typeof AppCampaignsCampaignIdNounsNewRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof AppCampaignsCampaignIdSessionsSessionIdRouteWithChildren
  '/campaigns/$campaignId/sessions/new': typeof AppCampaignsCampaignIdSessionsNewRoute
  '/campaigns/$campaignId/maps/': typeof AppCampaignsCampaignIdMapsIndexRoute
  '/campaigns/$campaignId/nouns/': typeof AppCampaignsCampaignIdNounsIndexRoute
  '/campaigns/$campaignId/sessions/': typeof AppCampaignsCampaignIdSessionsIndexRoute
  '/campaigns/$campaignId/maps/$mapId/edit': typeof AppCampaignsCampaignIdMapsMapIdEditRoute
  '/campaigns/$campaignId/nouns/$nounId/edit': typeof AppCampaignsCampaignIdNounsNounIdEditRoute
  '/campaigns/$campaignId/sessions/$sessionId/edit': typeof AppCampaignsCampaignIdSessionsSessionIdEditRoute
  '/campaigns/$campaignId/maps/$mapId/': typeof AppCampaignsCampaignIdMapsMapIdIndexRoute
  '/campaigns/$campaignId/nouns/$nounId/': typeof AppCampaignsCampaignIdNounsNounIdIndexRoute
  '/campaigns/$campaignId/sessions/$sessionId/': typeof AppCampaignsCampaignIdSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/campaigns/$campaignId/edit': typeof AppCampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/settings': typeof AppCampaignsCampaignIdSettingsRoute
  '/campaigns/$campaignId/timeline': typeof AppCampaignsCampaignIdTimelineRoute
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/maps/new': typeof AppCampaignsCampaignIdMapsNewRoute
  '/campaigns/$campaignId/nouns/new': typeof AppCampaignsCampaignIdNounsNewRoute
  '/campaigns/$campaignId/sessions/new': typeof AppCampaignsCampaignIdSessionsNewRoute
  '/campaigns/$campaignId/maps': typeof AppCampaignsCampaignIdMapsIndexRoute
  '/campaigns/$campaignId/nouns': typeof AppCampaignsCampaignIdNounsIndexRoute
  '/campaigns/$campaignId/sessions': typeof AppCampaignsCampaignIdSessionsIndexRoute
  '/campaigns/$campaignId/maps/$mapId/edit': typeof AppCampaignsCampaignIdMapsMapIdEditRoute
  '/campaigns/$campaignId/nouns/$nounId/edit': typeof AppCampaignsCampaignIdNounsNounIdEditRoute
  '/campaigns/$campaignId/sessions/$sessionId/edit': typeof AppCampaignsCampaignIdSessionsSessionIdEditRoute
  '/campaigns/$campaignId/maps/$mapId': typeof AppCampaignsCampaignIdMapsMapIdIndexRoute
  '/campaigns/$campaignId/nouns/$nounId': typeof AppCampaignsCampaignIdNounsNounIdIndexRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof AppCampaignsCampaignIdSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRouteWithChildren
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/campaigns/$campaignId/edit': typeof AppCampaignsCampaignIdEditRoute
  '/_app/campaigns/$campaignId/nouns': typeof AppCampaignsCampaignIdNounsRouteWithChildren
  '/_app/campaigns/$campaignId/sessions': typeof AppCampaignsCampaignIdSessionsRouteWithChildren
  '/_app/campaigns/$campaignId/settings': typeof AppCampaignsCampaignIdSettingsRoute
  '/_app/campaigns/$campaignId/timeline': typeof AppCampaignsCampaignIdTimelineRoute
  '/_app/campaigns/$campaignId/': typeof AppCampaignsCampaignIdIndexRoute
  '/_app/campaigns/$campaignId/maps/$mapId': typeof AppCampaignsCampaignIdMapsMapIdRouteWithChildren
  '/_app/campaigns/$campaignId/maps/new': typeof AppCampaignsCampaignIdMapsNewRoute
  '/_app/campaigns/$campaignId/nouns/$nounId': typeof AppCampaignsCampaignIdNounsNounIdRouteWithChildren
  '/_app/campaigns/$campaignId/nouns/new': typeof AppCampaignsCampaignIdNounsNewRoute
  '/_app/campaigns/$campaignId/sessions/$sessionId': typeof AppCampaignsCampaignIdSessionsSessionIdRouteWithChildren
  '/_app/campaigns/$campaignId/sessions/new': typeof AppCampaignsCampaignIdSessionsNewRoute
  '/_app/campaigns/$campaignId/maps/': typeof AppCampaignsCampaignIdMapsIndexRoute
  '/_app/campaigns/$campaignId/nouns/': typeof AppCampaignsCampaignIdNounsIndexRoute
  '/_app/campaigns/$campaignId/sessions/': typeof AppCampaignsCampaignIdSessionsIndexRoute
  '/_app/campaigns/$campaignId/maps/$mapId/edit': typeof AppCampaignsCampaignIdMapsMapIdEditRoute
  '/_app/campaigns/$campaignId/nouns/$nounId/edit': typeof AppCampaignsCampaignIdNounsNounIdEditRoute
  '/_app/campaigns/$campaignId/sessions/$sessionId/edit': typeof AppCampaignsCampaignIdSessionsSessionIdEditRoute
  '/_app/campaigns/$campaignId/maps/$mapId/': typeof AppCampaignsCampaignIdMapsMapIdIndexRoute
  '/_app/campaigns/$campaignId/nouns/$nounId/': typeof AppCampaignsCampaignIdNounsNounIdIndexRoute
  '/_app/campaigns/$campaignId/sessions/$sessionId/': typeof AppCampaignsCampaignIdSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/campaigns'
    | '/login'
    | '/register'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/api/auth/$'
    | '/campaigns/'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/nouns'
    | '/campaigns/$campaignId/sessions'
    | '/campaigns/$campaignId/settings'
    | '/campaigns/$campaignId/timeline'
    | '/campaigns/$campaignId/'
    | '/campaigns/$campaignId/maps/$mapId'
    | '/campaigns/$campaignId/maps/new'
    | '/campaigns/$campaignId/nouns/$nounId'
    | '/campaigns/$campaignId/nouns/new'
    | '/campaigns/$campaignId/sessions/$sessionId'
    | '/campaigns/$campaignId/sessions/new'
    | '/campaigns/$campaignId/maps/'
    | '/campaigns/$campaignId/nouns/'
    | '/campaigns/$campaignId/sessions/'
    | '/campaigns/$campaignId/maps/$mapId/edit'
    | '/campaigns/$campaignId/nouns/$nounId/edit'
    | '/campaigns/$campaignId/sessions/$sessionId/edit'
    | '/campaigns/$campaignId/maps/$mapId/'
    | '/campaigns/$campaignId/nouns/$nounId/'
    | '/campaigns/$campaignId/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/campaigns/new'
    | '/api/auth/$'
    | '/campaigns'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/settings'
    | '/campaigns/$campaignId/timeline'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/maps/new'
    | '/campaigns/$campaignId/nouns/new'
    | '/campaigns/$campaignId/sessions/new'
    | '/campaigns/$campaignId/maps'
    | '/campaigns/$campaignId/nouns'
    | '/campaigns/$campaignId/sessions'
    | '/campaigns/$campaignId/maps/$mapId/edit'
    | '/campaigns/$campaignId/nouns/$nounId/edit'
    | '/campaigns/$campaignId/sessions/$sessionId/edit'
    | '/campaigns/$campaignId/maps/$mapId'
    | '/campaigns/$campaignId/nouns/$nounId'
    | '/campaigns/$campaignId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/about'
    | '/_app/campaigns'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/campaigns/$campaignId'
    | '/_app/campaigns/new'
    | '/api/auth/$'
    | '/_app/campaigns/'
    | '/_app/campaigns/$campaignId/edit'
    | '/_app/campaigns/$campaignId/nouns'
    | '/_app/campaigns/$campaignId/sessions'
    | '/_app/campaigns/$campaignId/settings'
    | '/_app/campaigns/$campaignId/timeline'
    | '/_app/campaigns/$campaignId/'
    | '/_app/campaigns/$campaignId/maps/$mapId'
    | '/_app/campaigns/$campaignId/maps/new'
    | '/_app/campaigns/$campaignId/nouns/$nounId'
    | '/_app/campaigns/$campaignId/nouns/new'
    | '/_app/campaigns/$campaignId/sessions/$sessionId'
    | '/_app/campaigns/$campaignId/sessions/new'
    | '/_app/campaigns/$campaignId/maps/'
    | '/_app/campaigns/$campaignId/nouns/'
    | '/_app/campaigns/$campaignId/sessions/'
    | '/_app/campaigns/$campaignId/maps/$mapId/edit'
    | '/_app/campaigns/$campaignId/nouns/$nounId/edit'
    | '/_app/campaigns/$campaignId/sessions/$sessionId/edit'
    | '/_app/campaigns/$campaignId/maps/$mapId/'
    | '/_app/campaigns/$campaignId/nouns/$nounId/'
    | '/_app/campaigns/$campaignId/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/campaigns/$campaignId': {
      id: '/_app/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AppCampaignsCampaignIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/campaigns/$campaignId/': {
      id: '/_app/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof AppCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/timeline': {
      id: '/_app/campaigns/$campaignId/timeline'
      path: '/timeline'
      fullPath: '/campaigns/$campaignId/timeline'
      preLoaderRoute: typeof AppCampaignsCampaignIdTimelineRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/settings': {
      id: '/_app/campaigns/$campaignId/settings'
      path: '/settings'
      fullPath: '/campaigns/$campaignId/settings'
      preLoaderRoute: typeof AppCampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/sessions': {
      id: '/_app/campaigns/$campaignId/sessions'
      path: '/sessions'
      fullPath: '/campaigns/$campaignId/sessions'
      preLoaderRoute: typeof AppCampaignsCampaignIdSessionsRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/nouns': {
      id: '/_app/campaigns/$campaignId/nouns'
      path: '/nouns'
      fullPath: '/campaigns/$campaignId/nouns'
      preLoaderRoute: typeof AppCampaignsCampaignIdNounsRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/edit': {
      id: '/_app/campaigns/$campaignId/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof AppCampaignsCampaignIdEditRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/sessions/': {
      id: '/_app/campaigns/$campaignId/sessions/'
      path: '/'
      fullPath: '/campaigns/$campaignId/sessions/'
      preLoaderRoute: typeof AppCampaignsCampaignIdSessionsIndexRouteImport
      parentRoute: typeof AppCampaignsCampaignIdSessionsRoute
    }
    '/_app/campaigns/$campaignId/nouns/': {
      id: '/_app/campaigns/$campaignId/nouns/'
      path: '/'
      fullPath: '/campaigns/$campaignId/nouns/'
      preLoaderRoute: typeof AppCampaignsCampaignIdNounsIndexRouteImport
      parentRoute: typeof AppCampaignsCampaignIdNounsRoute
    }
    '/_app/campaigns/$campaignId/maps/': {
      id: '/_app/campaigns/$campaignId/maps/'
      path: '/maps'
      fullPath: '/campaigns/$campaignId/maps/'
      preLoaderRoute: typeof AppCampaignsCampaignIdMapsIndexRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/sessions/new': {
      id: '/_app/campaigns/$campaignId/sessions/new'
      path: '/new'
      fullPath: '/campaigns/$campaignId/sessions/new'
      preLoaderRoute: typeof AppCampaignsCampaignIdSessionsNewRouteImport
      parentRoute: typeof AppCampaignsCampaignIdSessionsRoute
    }
    '/_app/campaigns/$campaignId/sessions/$sessionId': {
      id: '/_app/campaigns/$campaignId/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/campaigns/$campaignId/sessions/$sessionId'
      preLoaderRoute: typeof AppCampaignsCampaignIdSessionsSessionIdRouteImport
      parentRoute: typeof AppCampaignsCampaignIdSessionsRoute
    }
    '/_app/campaigns/$campaignId/nouns/new': {
      id: '/_app/campaigns/$campaignId/nouns/new'
      path: '/new'
      fullPath: '/campaigns/$campaignId/nouns/new'
      preLoaderRoute: typeof AppCampaignsCampaignIdNounsNewRouteImport
      parentRoute: typeof AppCampaignsCampaignIdNounsRoute
    }
    '/_app/campaigns/$campaignId/nouns/$nounId': {
      id: '/_app/campaigns/$campaignId/nouns/$nounId'
      path: '/$nounId'
      fullPath: '/campaigns/$campaignId/nouns/$nounId'
      preLoaderRoute: typeof AppCampaignsCampaignIdNounsNounIdRouteImport
      parentRoute: typeof AppCampaignsCampaignIdNounsRoute
    }
    '/_app/campaigns/$campaignId/maps/new': {
      id: '/_app/campaigns/$campaignId/maps/new'
      path: '/maps/new'
      fullPath: '/campaigns/$campaignId/maps/new'
      preLoaderRoute: typeof AppCampaignsCampaignIdMapsNewRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/maps/$mapId': {
      id: '/_app/campaigns/$campaignId/maps/$mapId'
      path: '/maps/$mapId'
      fullPath: '/campaigns/$campaignId/maps/$mapId'
      preLoaderRoute: typeof AppCampaignsCampaignIdMapsMapIdRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/sessions/$sessionId/': {
      id: '/_app/campaigns/$campaignId/sessions/$sessionId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/sessions/$sessionId/'
      preLoaderRoute: typeof AppCampaignsCampaignIdSessionsSessionIdIndexRouteImport
      parentRoute: typeof AppCampaignsCampaignIdSessionsSessionIdRoute
    }
    '/_app/campaigns/$campaignId/nouns/$nounId/': {
      id: '/_app/campaigns/$campaignId/nouns/$nounId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/nouns/$nounId/'
      preLoaderRoute: typeof AppCampaignsCampaignIdNounsNounIdIndexRouteImport
      parentRoute: typeof AppCampaignsCampaignIdNounsNounIdRoute
    }
    '/_app/campaigns/$campaignId/maps/$mapId/': {
      id: '/_app/campaigns/$campaignId/maps/$mapId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/maps/$mapId/'
      preLoaderRoute: typeof AppCampaignsCampaignIdMapsMapIdIndexRouteImport
      parentRoute: typeof AppCampaignsCampaignIdMapsMapIdRoute
    }
    '/_app/campaigns/$campaignId/sessions/$sessionId/edit': {
      id: '/_app/campaigns/$campaignId/sessions/$sessionId/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignId/sessions/$sessionId/edit'
      preLoaderRoute: typeof AppCampaignsCampaignIdSessionsSessionIdEditRouteImport
      parentRoute: typeof AppCampaignsCampaignIdSessionsSessionIdRoute
    }
    '/_app/campaigns/$campaignId/nouns/$nounId/edit': {
      id: '/_app/campaigns/$campaignId/nouns/$nounId/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignId/nouns/$nounId/edit'
      preLoaderRoute: typeof AppCampaignsCampaignIdNounsNounIdEditRouteImport
      parentRoute: typeof AppCampaignsCampaignIdNounsNounIdRoute
    }
    '/_app/campaigns/$campaignId/maps/$mapId/edit': {
      id: '/_app/campaigns/$campaignId/maps/$mapId/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignId/maps/$mapId/edit'
      preLoaderRoute: typeof AppCampaignsCampaignIdMapsMapIdEditRouteImport
      parentRoute: typeof AppCampaignsCampaignIdMapsMapIdRoute
    }
  }
}

interface AppCampaignsCampaignIdNounsNounIdRouteChildren {
  AppCampaignsCampaignIdNounsNounIdEditRoute: typeof AppCampaignsCampaignIdNounsNounIdEditRoute
  AppCampaignsCampaignIdNounsNounIdIndexRoute: typeof AppCampaignsCampaignIdNounsNounIdIndexRoute
}

const AppCampaignsCampaignIdNounsNounIdRouteChildren: AppCampaignsCampaignIdNounsNounIdRouteChildren =
  {
    AppCampaignsCampaignIdNounsNounIdEditRoute:
      AppCampaignsCampaignIdNounsNounIdEditRoute,
    AppCampaignsCampaignIdNounsNounIdIndexRoute:
      AppCampaignsCampaignIdNounsNounIdIndexRoute,
  }

const AppCampaignsCampaignIdNounsNounIdRouteWithChildren =
  AppCampaignsCampaignIdNounsNounIdRoute._addFileChildren(
    AppCampaignsCampaignIdNounsNounIdRouteChildren,
  )

interface AppCampaignsCampaignIdNounsRouteChildren {
  AppCampaignsCampaignIdNounsNounIdRoute: typeof AppCampaignsCampaignIdNounsNounIdRouteWithChildren
  AppCampaignsCampaignIdNounsNewRoute: typeof AppCampaignsCampaignIdNounsNewRoute
  AppCampaignsCampaignIdNounsIndexRoute: typeof AppCampaignsCampaignIdNounsIndexRoute
}

const AppCampaignsCampaignIdNounsRouteChildren: AppCampaignsCampaignIdNounsRouteChildren =
  {
    AppCampaignsCampaignIdNounsNounIdRoute:
      AppCampaignsCampaignIdNounsNounIdRouteWithChildren,
    AppCampaignsCampaignIdNounsNewRoute: AppCampaignsCampaignIdNounsNewRoute,
    AppCampaignsCampaignIdNounsIndexRoute:
      AppCampaignsCampaignIdNounsIndexRoute,
  }

const AppCampaignsCampaignIdNounsRouteWithChildren =
  AppCampaignsCampaignIdNounsRoute._addFileChildren(
    AppCampaignsCampaignIdNounsRouteChildren,
  )

interface AppCampaignsCampaignIdSessionsSessionIdRouteChildren {
  AppCampaignsCampaignIdSessionsSessionIdEditRoute: typeof AppCampaignsCampaignIdSessionsSessionIdEditRoute
  AppCampaignsCampaignIdSessionsSessionIdIndexRoute: typeof AppCampaignsCampaignIdSessionsSessionIdIndexRoute
}

const AppCampaignsCampaignIdSessionsSessionIdRouteChildren: AppCampaignsCampaignIdSessionsSessionIdRouteChildren =
  {
    AppCampaignsCampaignIdSessionsSessionIdEditRoute:
      AppCampaignsCampaignIdSessionsSessionIdEditRoute,
    AppCampaignsCampaignIdSessionsSessionIdIndexRoute:
      AppCampaignsCampaignIdSessionsSessionIdIndexRoute,
  }

const AppCampaignsCampaignIdSessionsSessionIdRouteWithChildren =
  AppCampaignsCampaignIdSessionsSessionIdRoute._addFileChildren(
    AppCampaignsCampaignIdSessionsSessionIdRouteChildren,
  )

interface AppCampaignsCampaignIdSessionsRouteChildren {
  AppCampaignsCampaignIdSessionsSessionIdRoute: typeof AppCampaignsCampaignIdSessionsSessionIdRouteWithChildren
  AppCampaignsCampaignIdSessionsNewRoute: typeof AppCampaignsCampaignIdSessionsNewRoute
  AppCampaignsCampaignIdSessionsIndexRoute: typeof AppCampaignsCampaignIdSessionsIndexRoute
}

const AppCampaignsCampaignIdSessionsRouteChildren: AppCampaignsCampaignIdSessionsRouteChildren =
  {
    AppCampaignsCampaignIdSessionsSessionIdRoute:
      AppCampaignsCampaignIdSessionsSessionIdRouteWithChildren,
    AppCampaignsCampaignIdSessionsNewRoute:
      AppCampaignsCampaignIdSessionsNewRoute,
    AppCampaignsCampaignIdSessionsIndexRoute:
      AppCampaignsCampaignIdSessionsIndexRoute,
  }

const AppCampaignsCampaignIdSessionsRouteWithChildren =
  AppCampaignsCampaignIdSessionsRoute._addFileChildren(
    AppCampaignsCampaignIdSessionsRouteChildren,
  )

interface AppCampaignsCampaignIdMapsMapIdRouteChildren {
  AppCampaignsCampaignIdMapsMapIdEditRoute: typeof AppCampaignsCampaignIdMapsMapIdEditRoute
  AppCampaignsCampaignIdMapsMapIdIndexRoute: typeof AppCampaignsCampaignIdMapsMapIdIndexRoute
}

const AppCampaignsCampaignIdMapsMapIdRouteChildren: AppCampaignsCampaignIdMapsMapIdRouteChildren =
  {
    AppCampaignsCampaignIdMapsMapIdEditRoute:
      AppCampaignsCampaignIdMapsMapIdEditRoute,
    AppCampaignsCampaignIdMapsMapIdIndexRoute:
      AppCampaignsCampaignIdMapsMapIdIndexRoute,
  }

const AppCampaignsCampaignIdMapsMapIdRouteWithChildren =
  AppCampaignsCampaignIdMapsMapIdRoute._addFileChildren(
    AppCampaignsCampaignIdMapsMapIdRouteChildren,
  )

interface AppCampaignsCampaignIdRouteChildren {
  AppCampaignsCampaignIdEditRoute: typeof AppCampaignsCampaignIdEditRoute
  AppCampaignsCampaignIdNounsRoute: typeof AppCampaignsCampaignIdNounsRouteWithChildren
  AppCampaignsCampaignIdSessionsRoute: typeof AppCampaignsCampaignIdSessionsRouteWithChildren
  AppCampaignsCampaignIdSettingsRoute: typeof AppCampaignsCampaignIdSettingsRoute
  AppCampaignsCampaignIdTimelineRoute: typeof AppCampaignsCampaignIdTimelineRoute
  AppCampaignsCampaignIdIndexRoute: typeof AppCampaignsCampaignIdIndexRoute
  AppCampaignsCampaignIdMapsMapIdRoute: typeof AppCampaignsCampaignIdMapsMapIdRouteWithChildren
  AppCampaignsCampaignIdMapsNewRoute: typeof AppCampaignsCampaignIdMapsNewRoute
  AppCampaignsCampaignIdMapsIndexRoute: typeof AppCampaignsCampaignIdMapsIndexRoute
}

const AppCampaignsCampaignIdRouteChildren: AppCampaignsCampaignIdRouteChildren =
  {
    AppCampaignsCampaignIdEditRoute: AppCampaignsCampaignIdEditRoute,
    AppCampaignsCampaignIdNounsRoute:
      AppCampaignsCampaignIdNounsRouteWithChildren,
    AppCampaignsCampaignIdSessionsRoute:
      AppCampaignsCampaignIdSessionsRouteWithChildren,
    AppCampaignsCampaignIdSettingsRoute: AppCampaignsCampaignIdSettingsRoute,
    AppCampaignsCampaignIdTimelineRoute: AppCampaignsCampaignIdTimelineRoute,
    AppCampaignsCampaignIdIndexRoute: AppCampaignsCampaignIdIndexRoute,
    AppCampaignsCampaignIdMapsMapIdRoute:
      AppCampaignsCampaignIdMapsMapIdRouteWithChildren,
    AppCampaignsCampaignIdMapsNewRoute: AppCampaignsCampaignIdMapsNewRoute,
    AppCampaignsCampaignIdMapsIndexRoute: AppCampaignsCampaignIdMapsIndexRoute,
  }

const AppCampaignsCampaignIdRouteWithChildren =
  AppCampaignsCampaignIdRoute._addFileChildren(
    AppCampaignsCampaignIdRouteChildren,
  )

interface AppCampaignsRouteChildren {
  AppCampaignsCampaignIdRoute: typeof AppCampaignsCampaignIdRouteWithChildren
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsCampaignIdRoute: AppCampaignsCampaignIdRouteWithChildren,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
